=== DiegoSabir/MarkupLanguage/Estudiar/Ivan/dtd/clientinfo.dtd
<!ELEMENT informacioncliente (desc?, servicetype, servertype, t:cliente, s:cliente, connection*)>
<!ATTLIST informacioncliente 
name CDATA #FIXED "WoeRO" 
typegame CDATA #FIXED "MMORPG"
xmlns:t CDATA #FIXED "http://www.woero.com/download/tclientes/"
xmlns:s CDATA #FIXED "http://www.woero.com/download/sclientes/">
<!ELEMENT t:cliente (t:name, t:normal, t:full)>
<!ELEMENT t:name (#PCDATA)>
<!ELEMENT t:normal (#PCDATA)>
<!ELEMENT t:full (#PCDATA)>
<!ELEMENT s:cliente (s:name, s:normal, s:full)>
<!ELEMENT s:name (#PCDATA)>
<!ELEMENT s:normal (#PCDATA)>
<!ELEMENT s:full (#PCDATA)>
<!ELEMENT desc (#PCDATA)>
<!ELEMENT servicetype (#PCDATA)>
<!ELEMENT servertype (#PCDATA)>
<!ELEMENT connection (data_ini, display, address, port, version, langtype+, account, usuarios?, (registrationaccount1 | registrationaccount2))>
<!ATTLIST connection 
servidor (1 | 2) #REQUIRED
tipo (PlayerKill | DontPlayerKill) #REQUIRED
Online (Pocas | Muchas) "Muchas">
<!ELEMENT data_ini EMPTY>
<!ENTITY  % data
"ano CDATA #REQUIRED
mes (Enero | Febrero | Marzo | Abril | Mayo | Junio | Julio | 
 Agosto | Septiembre | Octubre | Noviembre | Diciembre) #REQUIRED
 dia CDATA #REQUIRED">
 <!ATTLIST data_ini %data; >
<!ELEMENT display (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT port (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT langtype (#PCDATA)>
<!ELEMENT account (admin | responsible)*>
<!ELEMENT admin (#PCDATA)>
<!ATTLIST admin id ID #REQUIRED>
<!ELEMENT responsible (#PCDATA)>
<!ATTLIST responsible ref IDREFS #IMPLIED>
<!ELEMENT usuarios (userprueba)*>
<!ELEMENT userprueba (#PCDATA)>
<!ATTLIST userprueba codigos NMTOKENS #REQUIRED>
<!ELEMENT registrationaccount1 (#PCDATA)>
<!ELEMENT registrationaccount2 (#PCDATA)>

=== DiegoSabir/MarkupLanguage/Estudiar/Ivan/dtd/clientinfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE informacioncliente SYSTEM "clientinfo.dtd">
<informacioncliente name="WoeRO" typegame="MMORPG" xmlns:t="http://www.woero.com/download/tclientes/" xmlns:s="http://www.woero.com/download/sclientes/">
  <desc>Información Cliente Ragnarok</desc>
  <servicetype>Alemania</servicetype>
  <servertype>sakray</servertype>
  <t:cliente>
    <t:name>WoeRO Third Job</t:name>
    <t:normal>Installer Normal Third</t:normal>
    <t:full>Installer Full Third</t:full>
   </t:cliente>
  <s:cliente>
    <s:name>WoeRO Second Jobs</s:name>
    <s:normal>Installer Normal Second</s:normal>
    <s:full>Installer Full Second</s:full>
  </s:cliente>
  <connection servidor="1" tipo="PlayerKill" Online="Muchas">
    <data_ini ano="2012" mes="Enero" dia="10"/>
    <display>WoeRO Third Job</display>
    <address>55.34.127.0</address>
    <port>6901</port>
    <version>1</version>
    <langtype>10</langtype>
    <account> 
            <admin id="A1000002">&apos;GM General&apos;</admin>
            <admin id="A1000003">GM Sprites</admin>
            <admin id="A1000228">GM Scrips</admin>
            <admin id="A1001093">GM Events</admin>
            <admin id="A1000289">GM Support</admin>
            <responsible ref="A1000002">Encargado del sistema y gestión del servidor</responsible>
            <responsible ref="A1000003">Encargado de crear Sprites</responsible>
            <responsible ref="A1000228">Encargado de crear Scrips</responsible>
            <responsible ref="A1001093 A1000289">Encargado de crear eventos en el juego</responsible>
            <responsible ref="A1001093 A1000289">Encargado de atender a los usuarios</responsible>
    </account>
    <usuarios>
        <userprueba codigos="3541 256 89">Ivan&gt;Pablo</userprueba>
        <userprueba codigos="8723 234 89">Diego&lt;Pablo</userprueba>
        <userprueba codigos="9156 245 89">&quot;Uxia, Alex, Fran&quot;</userprueba>
    </usuarios>
    <registrationaccount1>_m &amp; _f</registrationaccount1> 
  </connection>
  <connection servidor="2" tipo="DontPlayerKill" Online="Pocas">
    <data_ini ano="2010" mes="Noviembre" dia="21"/>
    <display>WoeRO Second Job</display>
    <address>54.93.127.0</address>
    <port>6901</port>
    <version>1</version>
    <langtype>10</langtype>
    <account> 
            <admin id="A2000002">&apos;GM General&apos;</admin>
            <admin id="A2000003">GM Sprites</admin>
            <admin id="A2000228">GM Scrips</admin>
            <admin id="A2001093">GM Events</admin>
            <admin id="A2000289">GM Support</admin>
            <responsible ref="A2000002">Encargado del sistema y gestión del servidor</responsible>
            <responsible ref="A2000003">Encargado de crear Sprites</responsible>
            <responsible ref="A2000228">Encargado de crear Scrips</responsible>
            <responsible ref="A2001093 A2000289">Encargado de crear eventos en el juego</responsible>
            <responsible ref="A2001093 A2000289">Encargado de atender a los usuarios</responsible>
    </account>
    <usuarios>
        <userprueba codigos="3542 257 90">Ivan&gt;Pablo</userprueba>
        <userprueba codigos="8724 235 90">Diego&lt;Pablo</userprueba>
        <userprueba codigos="9155 246 90">&quot;Uxia, Alex, Fran&quot;</userprueba>
    </usuarios>
    <registrationaccount2>_m &amp; _f</registrationaccount2> 
  </connection> 
</informacioncliente>
