=== DiegoSabir/MarkupLanguage/Estudiar/Ivan/chema/clientinfo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="informacioncliente">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="desc" type="xs:string"/>
        <xs:element name="servicetype" type="xs:string"/>
        <xs:element name="servertype" type="xs:string"/>
        <xs:element ref="connection"/>
      </xs:sequence>
<xs:attribute name="name" type="xs:string"/>
<xs:attribute name="typegame" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="connection">
  <xs:complexType>
  <xs:sequence>
<xs:element ref="data_ini"/>
<xs:element name="display" type="xs:string"/>
<xs:element name="address" type="xs:string"/>
<xs:element name="port" type="xs:unsignedLong"/>
<xs:element name="version" type="xs:unsignedByte"/>
<xs:element name="langtype" type="xs:unsignedByte"/>
<xs:element ref="account"/>
<xs:element ref="usuarios"/>
<xs:element name="registrationaccount" type="xs:string"/>
  </xs:sequence>
<xs:attribute name="servidor" type="xs:unsignedByte" use="required"/>
<xs:attribute name="tipo" type="xs:string" use="required"/>
<xs:attribute name="Online" type="xs:string" use="required"/>
  </xs:complexType>
  </xs:element>
  
<xs:element name="data_ini">
<xs:complexType>
<xs:attribute name="ano" type="xs:unsignedLong" use="required"/>
<xs:attribute name="mes" type="xs:string" use="required"/>
<xs:attribute name="dia" type="xs:unsignedByte" use="required"/>
</xs:complexType>
</xs:element>

<xs:element name="account">
<xs:complexType>
 <xs:sequence>
        <xs:element ref="admin" maxOccurs="unbounded"/>
        <xs:element ref="responsible" maxOccurs="unbounded"/>
</xs:sequence>
</xs:complexType>
</xs:element>

<xs:element name="admin">
<xs:complexType>
    <xs:simpleContent>
		  <xs:extension base="tipoNomeLongo">
<xs:attribute name="id" type="IDadmin" use="required"/>
		  </xs:extension>
		</xs:simpleContent>
</xs:complexType>
</xs:element>

<xs:element name="responsible">
<xs:complexType>
    <xs:simpleContent>
		  <xs:extension base="tipoNomeLongo">
			<xs:attribute name="ref" type="REFresponsable"  use="required"/>
      </xs:extension>
		</xs:simpleContent>
</xs:complexType>
</xs:element>

<xs:element name="usuarios">
<xs:complexType>
 <xs:sequence>
        <xs:element ref="userprueba" maxOccurs="unbounded"/>
</xs:sequence>
</xs:complexType>
</xs:element>

<xs:element name="userprueba">
<xs:complexType>
<xs:simpleContent>
		  <xs:extension base="tipoNomeLongo">
			<xs:attribute name="codigos" type="tipoCodigo"  use="required"/>
      </xs:extension>
</xs:simpleContent>
</xs:complexType>
</xs:element>

 <xs:simpleType name="IDadmin">
 <xs:restriction base="xs:string">
 <xs:pattern value="A[0-9]{7}"/>
 </xs:restriction>
 </xs:simpleType>
 
 <xs:simpleType name="REFresponsable">
 <xs:restriction base="xs:string">
 <xs:pattern value="[0-9]{7}A"/>
 </xs:restriction>
 </xs:simpleType>
 
  <xs:simpleType name="tipoCodigo">
 <xs:restriction base="xs:string">
 <xs:pattern value="[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]"/>
 </xs:restriction>
 </xs:simpleType>

<xs:simpleType name ="tipoNomeLongo">
<xs:restriction base="xs:string">
<xs:maxLength value="150"/>
</xs:restriction> 
 </xs:simpleType>

</xs:schema>

=== DiegoSabir/MarkupLanguage/Estudiar/Ivan/chema/clientinfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- IVAN SANTANA FERNANDEZ-->
<informacioncliente xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="clientinfo.xsd"
name="WoeRO" typegame="MMORPG">
  <desc>Información Cliente Ragnarok</desc>
  <servicetype>Alemania</servicetype>
  <servertype>sakray</servertype>
  <connection servidor="1" tipo="PlayerKill" Online="Muchas">
    <data_ini ano="2012" mes="Enero" dia="10"/>
    <display>WoeRO Third Job</display>
    <address>55.34.127.0</address>
    <port>6901</port>
    <version>1</version>
    <langtype>10</langtype>
    <account> 
            <admin id="A1000002">GM General</admin>
            <admin id="A1000003">GM Sprites</admin>
            <admin id="A1000228">GM Scrips</admin>
            <admin id="A1001093">GM Events</admin>
            <admin id="A1000289">GM Support</admin>
            <responsible ref="1000002A">Encargado del sistema y gestión del servidor</responsible>
            <responsible ref="1000003A">Encargado de crear Sprites</responsible>
            <responsible ref="1000228A">Encargado de crear Scrips</responsible>
            <responsible ref="1001093A">Encargado de crear eventos en el juego</responsible>
            <responsible ref="1000289A">Encargado de atender a los usuarios</responsible>
    </account>
    <usuarios>
        <userprueba codigos="354125689">Pablo</userprueba>
        <userprueba codigos="872323489">Diego</userprueba>
        <userprueba codigos="915624589">Uxia</userprueba>
        <userprueba codigos="915624589">Uxia</userprueba>
    </usuarios>
    <registrationaccount>_m  _f</registrationaccount> 
  </connection>
</informacioncliente>
