=== DiegoSabir/MarkupLanguage/Estudiar/Diego/ApuntesDTD.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT selecciones (equipo+)>
<!ELEMENT equipo (cuerpotecnico, plantilla)>
<!ATTLIST equipo 
sigla CDATA #REQUIRED
federacion CDATA #REQUIRED>
<!ELEMENT cuerpotecnico (tecnico+)>
<!ELEMENT tecnico (#PCDATA)>
<!ATTLIST tecnico
funcion CDATA #REQUIRED>
<!ELEMENT plantilla (jugador+)>
<!ELEMENT jugador (nombrecompleto, rol+, club+, posicion+)>
<!ATTLIST jugador
dorsal CDATA #REQUIRED>
<!ELEMENT nombrecompleto (#PCDATA)>
<!ELEMENT rol (#PCDATA)>
<!ELEMENT club (#PCDATA)>

=== DiegoSabir/MarkupLanguage/Estudiar/Diego/ApuntesDTD.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- DIEGO RIBAS GONZALEZ -->
<!DOCTYPE selecciones SYSTEM "ApuntesDTD.dtd">
<selecciones>
  <equipo sigla="CBF" federacion="CONMEBOL">
		<cuerpotecnico>
				<tecnico funcion="Entrenador">Tite</tecnico>
				<tecnico funcion="Segundo Entrenador">Cleber Xavier</tecnico>
				<tecnico funcion="Segundo Entrenador">Matheus Bachi</tecnico>
				<tecnico funcion="Entrenador de Porteros">Claudio Taffarel</tecnico>
				<tecnico funcion="Preparador Fisico">Fabio Mahseredijian</tecnico>
		</cuerpotecnico>
		<plantilla>
			<jugador dorsal="20">
				<nombrecompleto>Vinicius Jose Paixao de Oliveira Junior</nombrecompleto>
				<rol>Delantero</rol>
        <club>Real Madrid F.C</club>
			</jugador>
		</plantilla>
	</equipo>
</selecciones>
