=== DiegoSabir/MarkupLanguage/Estudiar/Diego/ApuntesXSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="selecciones">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="equipo" maxOccurs="32"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	
	<xs:element name="equipo">
		<xs:complexType>
			<xs:all>
				<xs:element ref="cuerpotecnico"/>
				<xs:element ref="plantilla"/>
			</xs:all>
			<xs:attribute name="sigla" type="xs:string" use="required"/>
			<xs:attribute name="federacion" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	
	
	<xs:element name="cuerpotecnico">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tecnico" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	
	<xs:element name="tecnico">
		<xs:complexType>
		  <xs:simpleContent>
        <xs:extension base="TipoNombreLargo">
		        <xs:attribute name="funcion" type="espacios" use="required"/>
		      </xs:extension>
		  </xs:simpleContent>
		</xs:complexType>
	</xs:element>



	<xs:element name="plantilla">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="jugador" maxOccurs="23"/>
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="clubunico">
		  <xs:selector xpath="jugador"/>
      <xs:field xpath="club"/>
		</xs:unique>
	</xs:element>	
	
	
	<xs:element name="jugador">
	
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nombrecompleto" type="TipoNombreLargo"/>
				<xs:element name="rol" type="TipoNombreLargo"/>
				<xs:element name="club" type="TipoNombreLargo"/>
			</xs:sequence>
			<xs:attribute name="dorsal" type="tipoNumero" use="required"/>
		</xs:complexType>
	</xs:element>
	
	
<xs:simpleType name="TipoNombreLargo">
    <xs:restriction base="xs:string">
      <xs:maxLength value="150"/>
    </xs:restriction>
  </xs:simpleType>
	<xs:simpleType name="espacios">
    <xs:restriction base="xs:string">
      <xs:maxLength value="50"/>
      <xs:pattern value="[A-ZÁÉÍÓÚÑÇ]([\sA-Za-záéíóúñ])+"/>
      <xs:whiteSpace value="collapse"/>
    </xs:restriction>
  </xs:simpleType>
	
	
	<xs:simpleType name="nombre">
		<xs:restriction base="xs:string">
			<xs:maxLength value="100"/>
		</xs:restriction>
	</xs:simpleType>
	
	
	<xs:simpleType name="tipoNumero">
    <xs:restriction base="xs:unsignedShort">
        <xs:minInclusive value="1"/>
        <xs:maxInclusive value="99"/>
    </xs:restriction>
  </xs:simpleType>
	
</xs:schema>

=== DiegoSabir/MarkupLanguage/Estudiar/Diego/ApuntesXSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- DIEGO RIBAS GONZALEZ -->
<selecciones xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="ApuntesXSD.xsd">
  <equipo sigla="CBF" federacion="CONMEBOL" rankingFIFA="1">
  
  
  <juntadirectiva>
    <presidente>Pepe</presidente> 
  </juntadirectiva>
  
  
		<cuerpotecnico>
      <tecnico funcion="Entrenador">Tite</tecnico>
      <tecnico funcion="Segundo Entrenador">Cleber Xavier</tecnico>
      <tecnico funcion="Segundo Entrenador">Matheus Bachi</tecnico>
      <tecnico funcion="Entrenador de Porteros">Claudio Taffarel</tecnico>
      <tecnico funcion="Preparador Fisico">Fabio Mahseredijian</tecnico>
		</cuerpotecnico>
			
		<plantilla>
			<jugador dorsal="20">
				<nombrecompleto>Vinicius Jose Paixao de Oliveira Junior</nombrecompleto>
				<rol>Delantero</rol>
				<club>Real Madrid F.C.</club>
			</jugador>
				
		</plantilla>
	</equipo>
</selecciones>
